# -*- coding: utf-8 -*-
"""Cosine Similarity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p6QQ5iSF-5fV2rvORzqqDHuHTTjX1oFR
"""

import tensorflow_text as text  # Registers the ops.

import tensorflow_hub as hub



import tensorflow_hub as hub
import tensorflow_text as text

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

from transformers import BertTokenizer, BertModel
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

def bert_preprocess(sentences):
    tokenized_input = tokenizer(sentences, padding=True, truncation=True, return_tensors="pt")
    return tokenized_input

def get_sentence_embedding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    with torch.no_grad():
        output = model(**preprocessed_text)
    return output.pooler_output

# Example usage
sentences = [
    "banana",
    "grapes",
    "mango",
    "jeff bezos",
]
embedding = get_sentence_embedding(sentences)
print(embedding)

from sklearn.metrics.pairwise import cosine_similarity

# Assuming e[0] and e[1] are the embeddings you want to compare
e = [
    [0.1, 0.2, 0.3],  # Example vector 1
    [0.4, 0.5, 0.6]   # Example vector 2
]

# Calculate cosine similarity
similarity = cosine_similarity([e[0]], [e[1]])

print("Cosine Similarity:", similarity[0][0])

from sklearn.metrics.pairwise import cosine_similarity

# Assuming e[0], e[1], and e[2] are the embeddings you want to compare
e = [
    [0.1, 0.2, 0.3],  # Example vector 1
    [0.4, 0.5, 0.6],  # Example vector 2
    [0.7, 0.8, 0.9]   # Example vector 3
]

# Calculate cosine similarity between the first and third vectors
similarity = cosine_similarity([e[0]], [e[2]])

print("Cosine Similarity:", similarity[0][0])

import pandas as pd

df = pd.read_csv("/content/Untitled spreadsheet - Sheet1.csv")
df.head(15)

from sklearn.model_selection import train_test_split

bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4", trainable=True)

def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

get_sentence_embeding([
    "How many departments are there at SSPM College of Engineering Kankavli?",
    "How many department"
     "About SSPM College of Engineering, Mumbai?"
    ]
)

from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([e[0]],[e[1]])

e = get_sentence_embeding([
    "About SSPM College of Engineering, Mumbai?",
    "Could you provide an overview of the Computer Science program offered at SSPM College of Engineering?",
    "How can I get in touch with the admissions office for inquiries regarding the application process?",
    "What engineering courses are offered at SSPM College of Engineering, Mumbai?",
    "how many branches?",
    "How many departments are there at SSPM College of Engineering Kankavli?"
    "How much cources at SSPM?",
    "Hello",
    "Provide some more information about computer branch",
    "How I get contact with admissin office?",
    "What is the admission process for undergraduate programs at SSPM College of Engineering Kankavli?",
    "What are the check-in and check-out procedures for hostel residents at SSPM College?",
    "How is the cleanliness and maintenance of hostel facilities ensured at SSPM College?",
    "Are students allowed to cook in the hostel premises at SSPM College?",
    "Could you provide an overview of the Computer Science program offered at SSPM College of Engineering?",
    "How can I get in touch with the admissions office for inquiries regarding the application process?",
    "What engineering courses are offered at SSPM College of Engineering, Mumbai?",
    "how many branches?",
    "How many departments are there at SSPM College of Engineering Kankavli?",
    "What is the admission process for undergraduate programs at SSPM College of Engineering Kankavli?",
    "Does SSPM College of Engineering Kankavli offer any scholarships?",
    "How does SSPM College of Engineering Kankavli support research and innovation?",
    "What extracurricular activities are available at SSPM College of Engineering Kankavli?",
    "How is the placement record of SSPM College of Engineering Kankavli?",
    "Are there any industry tie-ups or collaborations for internships at SSPM College of Engineering Kankavli?",
    "What are the eligibility criteria for admission to the first year of engineering programs at SSPM College of Engineering Kankavli?",
    "What entrance exams are accepted for admission to the first year at SSPM College of Engineering Kankavli?",
    "Can students from other states apply for admission to the first year at SSPM College of Engineering Kankavli?",
    "Is there any management quota for admission to the first year at SSPM College of Engineering Kankavli?",
    "What is the application process for admission to the first year at SSPM College of Engineering Kankavli?",
    "Are there any reservations or quotas for admission to the first year at SSPM College of Engineering Kankavli?",
    "What is the counseling process for admission to the first year at SSPM College of Engineering Kankavli?",
    "How are seats allotted during the counseling process for admission to the first year at SSPM College of Engineering Kankavli?",
    "Is there any document verification process during admission to the first year at SSPM College of Engineering Kankavli?",
    "Are there any scholarships available for first-year students at SSPM College of Engineering Kankavli?",
    "How do candidates check their admission status for the first year at SSPM College of Engineering Kankavli?",
    "Is there any provision for hostel accommodation for first-year students at SSPM College of Engineering Kankavli?",
    "What amenities are provided in the hostels for first-year students at SSPM College of Engineering Kankavli?",
    "Are there any special provisions for economically weaker section (EWS) students during admission to the first year at SSPM College of Engineering Kankavli?",
    "How does SSPM College of Engineering Kankavli assist first-year students in adapting to college life?",
    "What are the important dates and deadlines for admission to the first year at SSPM College of Engineering Kankavli?",
    "Can candidates apply for admission to multiple branches of engineering at SSPM College of Engineering Kankavli?:",
    "Is there any provision for spot admissions to the first year at SSPM College of Engineering Kankavli?",
    "How does SSPM College of Engineering Kankavli ensure transparency and fairness in the admission process for the first year?",
    "Are there any entrance exam coaching or preparation programs offered by SSPM College of Engineering Kankavli for first-year aspirants?",
    "What is the minimum age requirement for admission to the first year at SSPM College of Engineering Kankavli?",
    "Does SSPM College of Engineering Kankavli offer any reservations or quotas for sports or cultural achievements during admission to the first year?",
    "What are the academic facilities available at SSPM College of Engineering Kankavli?",
    "Does SSPM College of Engineering Kankavli offer any industry-oriented certification programs?",
    "Are there any provisions for student exchange programs at SSPM College of Engineering Kankavli?",
    "What is the student-faculty interaction like at SSPM College of Engineering Kankavli?",
    "Does SSPM College of Engineering Kankavli organize any industry-academic interface events?",
    "What are the opportunities for higher studies after completing graduation from SSPM College of Engineering Kankavli?",
    "Are there any alumni mentoring programs at SSPM College of Engineering Kankavli?",
    "How does SSPM College of Engineering Kankavli promote interdisciplinary learning?",
    "What is the role of industry experts in the curriculum design at SSPM College of Engineering Kankavli?",
    "Does SSPM College of Engineering Kankavli offer any foreign language courses?",
    "How does SSPM College of Engineering Kankavli support students in filing patents for their innovative projects?",
    "Is there a warden or hostel staff available to address the concerns of students at SSPM College?",
    "How are hostel fees structured at SSPM College?",
    "Are there any recreational facilities available in the hostels at SSPM College?",
    "Is there 24/7 security provided in the hostels at SSPM College?",
    "Are there any hostel rules and regulations that students need to follow at SSPM College?",
    "What is the process for applying for hostel accommodation at SSPM College?",
    "Is hostel accommodation compulsory for all students at SSPM College?",
    "How are hostel rooms allocated to students at SSPM College?",
    "Are there separate hostels for male and female students at SSPM College?",
    "What are the facilities available in the hostels at SSPM College?",
    "How many hostels are there at SSPM College?",
    "Does SSPM College provide hostel accommodation for students?",
    "What is the examination schedule like at SSPM College?",
    "How are examination dates determined at SSPM College?",
    "Are there any breaks during the examination session at SSPM College?",
    "How are examination centers allocated at SSPM College?",
    "What is the process for obtaining the examination timetable at SSPM College?",
    "How are examination papers set and evaluated at SSPM College?",
    "Are there any guidelines or rules that students need to follow during examinations at SSPM College?",
    "What happens in case a student misses an examination at SSPM College?",
    "How are practical examinations conducted at SSPM College?",
    "Are there any provisions for special accommodations during examinations at SSPM College?",
    "What programming languages are taught in the CSE curriculum at SSPM College of Engineering Kankvali?",
    "What career paths or opportunities are available for graduates from the CSE branch at SSPM College of Engineering Kankvali?",
    "Are there any exchange programs or opportunities for CSE students to study abroad or participate in international collaborations at SSPM College of Engineering Kankvali?",
    "How does SSPM College of Engineering Kankvali support CSE students in obtaining relevant certifications or professional credentials?",
    "Can you provide examples of recent achievements or accolades earned by CSE students or faculty members at SSPM College of Engineering Kankvali?",
    "What initiatives are in place to encourage innovation and entrepreneurship among CSE students at SSPM College of Engineering Kankvali?",
    "Are there any guest lectures or seminars conducted by industry experts specifically for CSE students at SSPM College of Engineering Kankvali?",
    "How does the CSE department at SSPM College of Engineering Kankvali support students interested in pursuing higher education or postgraduate studies?",
    "Can CSE students participate in research projects or collaborate with faculty members on research initiatives at SSPM College of Engineering Kankvali?",
    "What facilities and resources are available for CSE students, such as laboratories and software tools, at SSPM College of Engineering Kankvali?",
    "How does SSPM College of Engineering Kankvali ensure that CSE students are prepared for emerging technologies and industry trends?",
    "Are there internship programs specifically tailored for CSE students at SSPM College of Engineering Kankvali?",
    "Can you elaborate on the placement opportunities available for CSE students at SSPM College of Engineering Kankvali?",
    "Are there any student clubs or organizations dedicated to CSE-related activities at SSPM College of Engineering Kankvali?",
    "What types of hands-on projects or practical experiences do CSE students undertake at SSPM College of Engineering Kankvali?",
    "Does SSPM College of Engineering Kankvali have collaborations with industry partners specifically for CSE students?",
    "How qualified and experienced are the faculty members within the CSE department at SSPM College of Engineering Kankvali?",
    "What research areas are emphasized within the CSE department at SSPM College of Engineering Kankvali?",
    "Are there any specialized tracks or elective courses available within the CSE program at SSPM College of Engineering Kankvali?",
    "Could you provide an overview of the curriculum offered in the CSE branch at SSPM College of Engineering Kankvali?",
    "What is the total intake capacity for the Computer Science and Engineering (CSE) branch at SSPM College of Engineering Kankvali?",

]
)

from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([e[0]],[e[1]])